CREATE TABLE IF NOT EXISTS `CO_HSPTL_LNKNG` (
    `CO_SN` INT NOT NULL COMMENT '회사 일련번호',
    `HSPTL_SN` INT NOT NULL COMMENT '병원 일련번호',
    `REG_ID` VARCHAR(50) NULL COMMENT '등록자 ID',
    `REG_YMD` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    PRIMARY KEY (`CO_SN`, `HSPTL_SN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
