-- DDL generated from CodeIgniter Models
-- Assumptions made where explicit types were not found in validation rules.

-- 1. HSPTL_MNG (from HsptlMngModel)
CREATE TABLE IF NOT EXISTS `HSPTL_MNG` (
    `HSPTL_SN` INT AUTO_INCREMENT PRIMARY KEY COMMENT '병원 일련번호',
    `HSPTL_NM` VARCHAR(100) NOT NULL COMMENT '병원명',
    `PIC_NM` VARCHAR(50) NULL COMMENT '담당자명',
    `CNPL1` VARCHAR(50) NULL COMMENT '연락처1',
    `RGN` VARCHAR(10) NULL COMMENT '지역',
    `REG_ID` VARCHAR(50) NULL COMMENT '등록자 ID',
    `MDFCN_ID` VARCHAR(50) NULL COMMENT '수정자 ID',
    `DEL_YN` CHAR(1) DEFAULT 'N' COMMENT '삭제여부',
    `REG_YMD` DATETIME NULL COMMENT '등록일시',
    `MDFCN_YMD` DATETIME NULL COMMENT '수정일시'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. MNGR_MNG (from MngrMngModel)
CREATE TABLE IF NOT EXISTS `MNGR_MNG` (
    `MNGR_SN` INT AUTO_INCREMENT PRIMARY KEY COMMENT '관리자 일련번호',
    `MNGR_ID` VARCHAR(50) NOT NULL UNIQUE COMMENT '관리자 ID',
    `MNGR_NM` VARCHAR(50) NOT NULL COMMENT '관리자명',
    `MNGR_PSWD` VARCHAR(255) NOT NULL COMMENT '비밀번호',
    `HSPTL_SN` INT NULL COMMENT '병원 일련번호',
    CONSTRAINT `FK_MNGR_HSPTL` FOREIGN KEY (`HSPTL_SN`) REFERENCES `HSPTL_MNG` (`HSPTL_SN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. CHC_ARTCL_MNG (from ChcArtclMngModel)
CREATE TABLE IF NOT EXISTS `CHC_ARTCL_MNG` (
    `CHC_ARTCL_SN` INT AUTO_INCREMENT PRIMARY KEY COMMENT '선택항목 일련번호',
    `CKUP_ARTCL` VARCHAR(100) NOT NULL COMMENT '검사항목',
    `ARTCL_CODE` VARCHAR(10) DEFAULT NULL COMMENT '항목코드',
    `GNDR_SE` VARCHAR(1) DEFAULT 'C' COMMENT '성별구분 (M, F, C)',
    `CKUP_SE` VARCHAR(2) NULL COMMENT '검사구분',
    `CKUP_CST` VARCHAR(10) NOT NULL COMMENT '검사비용',
    `RMRK` VARCHAR(200) NULL COMMENT '비고',
    `AGREE_SUBMIT_YN` VARCHAR(1) DEFAULT 'N' COMMENT '동의서제출여부',
    `HSPTL_SN` INT NULL COMMENT '병원 일련번호',
    `REG_ID` VARCHAR(50) NULL COMMENT '등록자 ID',
    `MDFCN_ID` VARCHAR(50) NULL COMMENT '수정자 ID',
    `DEL_YN` CHAR(1) DEFAULT 'N' COMMENT '삭제여부',
    `REG_YMD` DATETIME NULL COMMENT '등록일시',
    `MDFCN_YMD` DATETIME NULL COMMENT '수정일시'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. CKUP_ARTCL_MNG (from CkupArtclMngModel)
CREATE TABLE IF NOT EXISTS `CKUP_ARTCL_MNG` (
    `CKUP_ARTCL_SN` INT AUTO_INCREMENT PRIMARY KEY COMMENT '검진항목 일련번호',
    `CKUP_SE` VARCHAR(50) NOT NULL COMMENT '검진구분',
    `CKUP_ARTCL` VARCHAR(100) NOT NULL COMMENT '검진항목명',
    `ARTCL_CODE` VARCHAR(10) DEFAULT NULL COMMENT '항목코드',
    `DSS` VARCHAR(100) NULL COMMENT '질환명',
    `GNDR_SE` VARCHAR(1) DEFAULT 'C' COMMENT '성별구분 (M, F, C)',
    `HSPTL_SN` INT NULL COMMENT '병원 일련번호',
    `REG_ID` VARCHAR(50) NULL COMMENT '등록자 ID',
    `MDFCN_ID` VARCHAR(50) NULL COMMENT '수정자 ID',
    `DEL_YN` CHAR(1) DEFAULT 'N' COMMENT '삭제여부',
    `REG_YMD` DATETIME NULL COMMENT '등록일시',
    `MDFCN_YMD` DATETIME NULL COMMENT '수정일시'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4-1. CKUP_ARTCL_MNG (from CkupArtclMngModel)
CREATE TABLE IF NOT EXISTS `CKUP_ARTCL_MNG` (
  `CKUP_ARTCL_SN` int(11) NOT NULL AUTO_INCREMENT COMMENT '검진항목 일련번호',
  `HSPTL_SN` int(11) DEFAULT NULL COMMENT '병원 일련번호',
  `CKUP_SE` varchar(50) NOT NULL COMMENT '검진구분',
  `CKUP_ARTCL` varchar(100) NOT NULL COMMENT '검진항목명',
  `ARTCL_CODE` varchar(10) DEFAULT NULL COMMENT '항목코드',
  `DSS` varchar(2000) DEFAULT NULL COMMENT '질환명',
  `GNDR_SE` varchar(1) DEFAULT 'C' COMMENT '성별구분 (M, F, C)',
  `CKUP_TYPE` varchar(2) DEFAULT NULL COMMENT '검사유형 기타(ET)대장내시경(CS)위내시경(GS)유방초음파(BU)골반초음파(PU)초음파(UT)CT(CT)',
  `CKUP_CST` varchar(10) NOT NULL COMMENT '검사비용',
  `RMRK` varchar(200) DEFAULT NULL COMMENT '비고',
  `REG_ID` varchar(50) DEFAULT NULL COMMENT '등록자 ID',
  `MDFCN_ID` varchar(50) DEFAULT NULL COMMENT '수정자 ID',
  `DEL_YN` char(1) DEFAULT 'N' COMMENT '삭제여부',
  `REG_YMD` datetime DEFAULT NULL COMMENT '등록일시',
  `MDFCN_YMD` datetime DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`CKUP_ARTCL_SN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. CO_MNG (from CoMngModel)
CREATE TABLE IF NOT EXISTS `CO_MNG` (
    `CO_SN` INT AUTO_INCREMENT PRIMARY KEY COMMENT '회사 일련번호',
    `CO_NM` VARCHAR(100) NOT NULL COMMENT '회사명',
    `PIC_NM` VARCHAR(50) NULL COMMENT '담당자명',
    `CNPL` VARCHAR(50) NULL COMMENT '연락처',
    `BGNG_YMD` DATE NULL COMMENT '검진시작일자',
    `END_YMD` DATE NULL COMMENT '검진종료일자',
    `REG_ID` VARCHAR(50) NULL COMMENT '등록자 ID',
    `MDFCN_ID` VARCHAR(50) NULL COMMENT '수정자 ID',
    `DEL_YN` CHAR(1) DEFAULT 'N' COMMENT '삭제여부',
    `REG_YMD` DATETIME NULL COMMENT '등록일시',
    `MDFCN_YMD` DATETIME NULL COMMENT '수정일시'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6. CKUP_TRGT (from CkupTrgtModel)
CREATE TABLE IF NOT EXISTS `CKUP_TRGT` (
   `CKUP_TRGT_SN` int(11) NOT NULL AUTO_INCREMENT COMMENT '검진대상자 일련번호',
  `CO_SN` int(11) DEFAULT NULL COMMENT '회사 일련번호',
  `CKUP_YYYY` varchar(4) NOT NULL COMMENT '검진년도',
  `CKUP_NAME` varchar(50) NOT NULL COMMENT '수검자명',
  `NAME` varchar(50) NOT NULL COMMENT '직원명',
  `BUSINESS_NUM` varchar(30) DEFAULT NULL COMMENT '사업자번호/사번',
  `BIRTHDAY` varchar(6) DEFAULT NULL COMMENT '생년월일(YYMMDD)',
  `PSWD` varchar(255) DEFAULT NULL COMMENT '비밀번호',
  `SEX` char(1) DEFAULT NULL COMMENT '성별',
  `TEL` varchar(13) DEFAULT NULL COMMENT '일반전화번호',
  `HANDPHONE` varchar(13) DEFAULT NULL COMMENT '휴대전화번호',
  `SUPPORT_FUND` varchar(50) DEFAULT NULL COMMENT '지원금',
  `FAMILY_SUPPORT_FUND` varchar(50) DEFAULT NULL COMMENT '가족지원금',
  `EMAIL` varchar(50) DEFAULT NULL COMMENT '이메일',
  `WORK_STATUS` varchar(20) DEFAULT NULL COMMENT '재직상태',
  `ASSIGN_CODE` varchar(20) DEFAULT NULL COMMENT '배정코드',
  `JOB` varchar(50) DEFAULT NULL COMMENT '직무',
  `RELATION` varchar(20) DEFAULT NULL COMMENT '관계',
  `AGREE_YN` varchar(1) DEFAULT 'N' COMMENT '약관동의 여부',
  `CHECKUP_TARGET_YN` char(1) DEFAULT 'N' COMMENT '검진대상여부',
  `RSVT_STTS` char(1) DEFAULT 'N' COMMENT '예약상태',
  `CKUP_YN` char(1) DEFAULT 'N' COMMENT '검진여부',
  `CKUP_HSPTL_SN` bigint(20) DEFAULT NULL COMMENT '검진병원 일련번호',
  `CKUP_RSVN_YMD` date DEFAULT NULL COMMENT '검진예약일자',
  `CKUP_GDS_SN` int(11) DEFAULT NULL COMMENT '검진상품일련번호',
  `REG_ID` varchar(50) DEFAULT NULL COMMENT '등록자 ID',
  `MDFCN_ID` varchar(50) DEFAULT NULL COMMENT '수정자 ID',
  `DEL_YN` char(1) DEFAULT 'N' COMMENT '삭제여부',
  `REG_YMD` datetime DEFAULT NULL COMMENT '등록일시',
  `MDFCN_YMD` datetime DEFAULT NULL COMMENT '수정일시',
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 12. DAY_CKUP_MNG (from DayCkupMngModel)
CREATE TABLE IF NOT EXISTS `DAY_CKUP_MNG` (
    `DAY_CKUP_MNG_SN` INT AUTO_INCREMENT PRIMARY KEY COMMENT '요일별검진관리 일련번호',
    `HSPTL_SN` INT NOT NULL COMMENT '병원 일련번호',
    `CKUP_YMD` DATE NOT NULL COMMENT '검진일자',
    `DAY_CKUP_SE` VARCHAR(10) NOT NULL COMMENT '요일구분(WEEKDAY/SAT)',
    `CKUP_SE` VARCHAR(10) NOT NULL COMMENT '검진구분(TOTAL/GS/CS/etc)',
    `MAX_CNT` INT DEFAULT 0 COMMENT '최대인원수',
    `CKUP_SE_CHC_CNT` INT DEFAULT 0 COMMENT '검진구분선택수',
    `REG_ID` VARCHAR(50) NULL COMMENT '등록자 ID',
    `MDFCN_ID` VARCHAR(50) NULL COMMENT '수정자 ID',
    `REG_YMD` DATETIME NULL COMMENT '등록일시',
    `MDFCN_YMD` DATETIME NULL COMMENT '수정일시'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 13. CO_HSPTL_LNKNG (from CoHsptlLnkngModel)
CREATE TABLE IF NOT EXISTS `CO_HSPTL_LNKNG` (
    `CO_SN` INT NOT NULL COMMENT '회사 일련번호',
    `HSPTL_SN` INT NOT NULL COMMENT '병원 일련번호',
    `REG_ID` VARCHAR(50) NULL COMMENT '등록자 ID',
    `REG_YMD` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    PRIMARY KEY (`CO_SN`, `HSPTL_SN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 14. CKUP_TRGT_MEMO (from CkupTrgtMemoModel)
CREATE TABLE IF NOT EXISTS `CKUP_TRGT_MEMO` (
    `CKUP_TRGT_MEMO_SN` INT AUTO_INCREMENT PRIMARY KEY COMMENT '검진대상자메모 일련번호',
    `CKUP_TRGT_SN` INT NOT NULL COMMENT '검진대상자 일련번호',
    `MEMO` TEXT NULL COMMENT '메모',
    `REG_ID` VARCHAR(50) NULL COMMENT '등록자 ID',
    `REG_YMD` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    `MDFCN_ID` VARCHAR(50) NULL COMMENT '수정자 ID',
    `MDFCN_YMD` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 15. RSVN_CKUP_GDS_ADD_CHC 
CREATE TABLE IF NOT EXISTS `RSVN_CKUP_GDS_ADD_CHC` (
  `RSVN_CKUP_GDS_ADD_CHC_SN` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '예약검진추가선택 일련번호',
  `CKUP_GDS_EXCEL_ADD_ARTCL_SN` int(11) DEFAULT NULL COMMENT '검진상품추가항목 일련번호',
  `CKUP_TRGT_SN` int(11) DEFAULT NULL COMMENT '검진대상 일련번호',
  `REG_ID` varchar(50) DEFAULT NULL COMMENT '등록자 ID',
  `MDFCN_ID` varchar(50) DEFAULT NULL COMMENT '수정자 ID',
  `DEL_YN` char(1) DEFAULT 'N' COMMENT '삭제여부',
  `REG_YMD` datetime DEFAULT NULL COMMENT '등록일시',
  `MDFCN_YMD` datetime DEFAULT NULL COMMENT '수정일시'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='예약검진상품추가선택';

-- 16. RSVN_CKUP_GDS_CHC_ARTCL 
CREATE TABLE IF NOT EXISTS `RSVN_CKUP_GDS_CHC_ARTCL` (
  `RSVN_CKUP_GDS_CHC_ARTCL_SN` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '예약검진선택항목 일련번호',
  `CKUP_GDS_EXCEL_CHC_ARTCL_SN` int(11) DEFAULT NULL COMMENT '검진상품선택항목 일련번호',
  `CKUP_TRGT_SN` int(11) DEFAULT NULL COMMENT '검진대상 일련번호',
  `REG_ID` varchar(50) DEFAULT NULL COMMENT '등록자 ID',
  `MDFCN_ID` varchar(50) DEFAULT NULL COMMENT '수정자 ID',
  `DEL_YN` char(1) DEFAULT 'N' COMMENT '삭제여부',
  `REG_YMD` datetime DEFAULT NULL COMMENT '등록일시',
  `MDFCN_YMD` datetime DEFAULT NULL COMMENT '수정일시'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='예약선택항목';

-- 17. RSVN_CKUP_TRGT_ADDR 
CREATE TABLE IF NOT EXISTS `RSVN_CKUP_TRGT_ADDR` (
    `RSVN_CKUP_TRGT_ADDR_SN`             INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '예약검진대상주소 일련번호',
	`CKUP_TRGT_SN`	INT(11) NOT NULL COMMENT '검진대상일련번호', 
    `ZIP_CODE`       VARCHAR(10) NOT NULL COMMENT '우편번호',
    `ADDR`        VARCHAR(255) NOT NULL COMMENT '기본 주소 (도로명/지번)',
    `ADDR2` VARCHAR(255) DEFAULT NULL COMMENT '상세 주소 (동, 호수 등)',
    `REG_YMD` DATETIME NULL COMMENT '등록일시',
    `MDFCN_YMD`     DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (`RSVN_CKUP_TRGT_ADDR_SN`)
)COMMENT='예약검진대상주소';

-- 18. CKUP_GDS_EXCEL_MNG (from CkupGdsExcelMngModel)
CREATE TABLE IF NOT EXISTS `CKUP_GDS_EXCEL_MNG` (
    `CKUP_GDS_EXCEL_MNG_SN` INT AUTO_INCREMENT PRIMARY KEY COMMENT '검진상품엑셀 일련번호',
    `HSPTL_SN` INT NOT NULL COMMENT '병원 일련번호',
    `CKUP_YYYY` VARCHAR(4) NOT NULL COMMENT '검진년도',
    `CKUP_GDS_NM` VARCHAR(100) NOT NULL COMMENT '검진상품명',
    `SPRT_SE` VARCHAR(10) NULL COMMENT '지원구분',
    `FAM_SPRT_SE` VARCHAR(10) NULL COMMENT '가족지원구분',
    `DEL_YN` CHAR(1) DEFAULT 'N' COMMENT '삭제여부',
    `REG_ID` VARCHAR(50) NULL COMMENT '등록자 ID',
    `MDFCN_ID` VARCHAR(50) NULL COMMENT '수정자 ID',
    `REG_YMD` DATETIME NULL COMMENT '등록일시',
    `MDFCN_YMD` DATETIME NULL COMMENT '수정일시'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='검진상품엑셀';

-- 19. CKUP_GDS_EXCEL_ARTCL (from CkupGdsExcelArtclModel)
CREATE TABLE IF NOT EXISTS `CKUP_GDS_EXCEL_ARTCL` (
    `CKUP_GDS_EXCEL_ARTCL_SN` INT AUTO_INCREMENT PRIMARY KEY COMMENT '검진상품엑셀항목 일련번호',
    `CKUP_GDS_EXCEL_MNG_SN` INT NULL COMMENT '검진상품엑셀 일련번호',
    `CKUP_SE` varchar(50) NOT NULL COMMENT '검진구분',
	`CKUP_ARTCL` varchar(100) NOT NULL COMMENT '검진항목명',
	`DSS` varchar(500) DEFAULT NULL COMMENT '질환명',
	`GNDR_SE` varchar(1) DEFAULT 'C' COMMENT '성별구분 (M, F, C)',
	`RMRK` varchar(200) DEFAULT NULL COMMENT '비고',
    `DEL_YN` CHAR(1) DEFAULT 'N' COMMENT '삭제여부'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='검진상품엑셀항목';

-- 20. CKUP_GDS_EXCEL_CHC_GROUP (from CkupGdsExcelChcGroupModel)
CREATE TABLE IF NOT EXISTS `CKUP_GDS_EXCEL_CHC_GROUP` (
    `CKUP_GDS_EXCEL_CHC_GROUP_SN` INT AUTO_INCREMENT PRIMARY KEY COMMENT '검진상품엑셀선택그룹 일련번호',
    `CKUP_GDS_EXCEL_MNG_SN` INT NULL COMMENT '검진상품엑셀 일련번호',
    `GROUP_NM` VARCHAR(100) NULL COMMENT '그룹명',
    `CHC_ARTCL_CNT` INT NULL COMMENT '선택가능항목수',
    `CHC_ARTCL_CNT2` int(11) DEFAULT NULL COMMENT '선택가능항목수2',
    `DEL_YN` CHAR(1) DEFAULT 'N' COMMENT '삭제여부'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='검진상품엑셀선택그룹';

-- 21. CKUP_GDS_EXCEL_CHC_ARTCL (from CkupGdsExeclChcArtclModel)
CREATE TABLE IF NOT EXISTS `CKUP_GDS_EXCEL_CHC_ARTCL` (
    `CKUP_GDS_EXCEL_CHC_ARTCL_SN` INT AUTO_INCREMENT PRIMARY KEY COMMENT '검진상품엑셀선택항목 일련번호',
    `CKUP_GDS_EXCEL_CHC_GROUP_SN` INT NULL COMMENT '검진상품엑셀선택그룹 일련번호',
    `CKUP_GDS_EXCEL_MNG_SN` INT NULL COMMENT '검진상품엑셀 일련번호',
    `CKUP_SE` varchar(50) NOT NULL COMMENT '검진구분',
	`CKUP_TYPE` varchar(2) DEFAULT NULL COMMENT '검사유형(기타,대장내시경,위내시경,유방초음파,골반초음파,초음파,CT)',
	`CKUP_ARTCL` varchar(100) NOT NULL COMMENT '검진항목명',
	`DSS` varchar(500) DEFAULT NULL COMMENT '질환명',
	`GNDR_SE` varchar(1) DEFAULT 'C' COMMENT '성별구분 (M, F, C)',
	`RMRK` varchar(200) DEFAULT NULL COMMENT '비고',
    `DEL_YN` CHAR(1) DEFAULT 'N' COMMENT '삭제여부'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='검진상품엑셀선택항목';

-- 22. CKUP_GDS_EXCEL_ADD_CHC (from CkupGdsExcelAddChcModel)
CREATE TABLE IF NOT EXISTS `CKUP_GDS_EXCEL_ADD_CHC` (
    `CKUP_GDS_EXCEL_ADD_CHC_SN` INT AUTO_INCREMENT PRIMARY KEY COMMENT '검진상품엑셀추가선택 일련번호',
    `CKUP_GDS_EXCEL_SN` INT NULL COMMENT '검진상품 일련번호',
    `CKUP_SE` varchar(50) NOT NULL COMMENT '검진구분',
	`CKUP_TYPE` varchar(2) DEFAULT NULL COMMENT '검사유형(기타,대장내시경,위내시경,유방초음파,골반초음파,초음파,CT)',
	`CKUP_ARTCL` varchar(100) NOT NULL COMMENT '검진항목명',
	`DSS` varchar(500) DEFAULT NULL COMMENT '질환명',
	`GNDR_SE` varchar(1) DEFAULT 'C' COMMENT '성별구분 (M, F, C)',
	`CKUP_CST` varchar(10) NOT NULL COMMENT '검사비용',
	`RMRK` varchar(200) DEFAULT NULL COMMENT '비고',
    `DEL_YN` CHAR(1) DEFAULT 'N' COMMENT '삭제여부'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='검진상품엑셀추가선택';

